spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jrx_datareport?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  profiles:
    active: dev
  hikari:
    minimum-idle: 5
    idle-timeout: 180000
    maximum-pool-size: 10
  batch:
    initialize-schema: always
  main:
    allow-bean-definition-overriding: true

logging:
  config: classpath:log4j2.xml

# 配置pagehelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#mybatis:
  #mapper-locations: data_report_parent/data_report/classpath*:mapper/*.xml
  #type-aliases-package: jrx.data.report.model

